### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LynnGuo666** [Arthed-Studios/SmartMoving#3]
[11:44:44 ERROR]: Thread dumps: 
Craft Scheduler Thread - 61 - SmartMoving:
        at java.base/java.lang.Thread.getStackTrace(Thread.java:2550)
        at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:87)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:77)
        at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
        at net.minecraft.world.level.levelgen.BitRandomSource.g(BitRandomSource.java:36)
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.playSound(CraftWorld.java:1842)
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.playSound(CraftWorld.java:1820)
        at SmartMoving-1.0.1-all.jar//com.github.ipecter.smartmoving.utils.WallJumpUtil.playWallJumpSound(WallJumpUtil.java:105)
        at SmartMoving-1.0.1-all.jar//com.github.ipecter.smartmoving.SMPlayer.lambda$startWallJump$5(SMPlayer.java:233)
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
[11:44:44 WARN]: [SmartMoving] Plugin SmartMoving v1.0.1 generated an exception while executing task 115
net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:83) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:45) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.world.level.levelgen.BitRandomSource.nextLong(BitRandomSource.java:36) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.playSound(CraftWorld.java:1842) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.playSound(CraftWorld.java:1820) ~[paper-1.19.3.jar:git-Paper-386]
        at com.github.ipecter.smartmoving.utils.WallJumpUtil.playWallJumpSound(WallJumpUtil.java:105) ~[SmartMoving-1.0.1-all.jar:?]
        at com.github.ipecter.smartmoving.SMPlayer.lambda$startWallJump$5(SMPlayer.java:233) ~[SmartMoving-1.0.1-all.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-386]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
        at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:79) ~[paper-1.19.3.jar:git-Paper-386]
        ... 12 more

Minecraft 1.19.3 Paper 386

**Comment by IPECTER** [comment]
Paper error.
